### PR TITLE
Fix for R package doc

### PR DESCRIPTION
**Pull request by escauley**
Fixed typos and added section on adding Conda channels

### CODE REVIEW

**Comment by kopardev** [comment]
@escauley ... can you look at the merge conflict and create a new PR and ping me.

**Comment by escauley** [comment]
Is there a way to see the merge conflict without having write access? For me, the grey button "Resolve conflicts" is greyed out and not clickable, and it says "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

Otherwise I can see what the differences are, but not where the conflict arises

**Comment by kopardev** [comment]
@kelly-sovacool can you please help @escauley with this?

**Comment by kelly-sovacool** [comment]
> Is there a way to see the merge conflict without having write access? For me, the grey button "Resolve conflicts" is greyed out and not clickable, and it says "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."
> 
> Otherwise I can see what the differences are, but not where the conflict arises

@escauley GitHub won't let us resolve conflicts on the web because these conflicts are too complex. I can walk you through how to resolve them via the CLI if needed, let me know!

**Comment by escauley** [comment]
Created a new branch and pull request: #13

**Pull request closed without merging**
